services:

  caddy:
    image: caddy:latest
    container_name: mountyhall-caddy
    build:
      context: ./caddy
      dockerfile_inline: |
        FROM caddy:builder AS builder
        RUN xcaddy build --with github.com/caddy-dns/ovh
        FROM caddy:latest
        COPY --from=builder /usr/bin/caddy /usr/bin/caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp" # Optionnel : pour le support de HTTP/3
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
    environment:
      - OVH_APPLICATION_KEY=${OVH_APPLICATION_KEY}
      - OVH_APPLICATION_SECRET=${OVH_APPLICATION_SECRET}
      - OVH_CONSUMER_KEY=${OVH_CONSUMER_KEY}
      - MY_DOMAIN=${MY_DOMAIN}
      - MY_API_DOMAIN=${MY_API_DOMAIN}
      - MY_DB_DOMAIN=${MY_DB_DOMAIN}
      - HTPASSWD_USERNAME=${HTPASSWD_USERNAME}
      - HTPASSWD_PASSWORD=${HTPASSWD_PASSWORD}
    depends_on:
      - frontend
    networks:
      - mountyhall-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mountyhall-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/instance:/app/instance
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - FLASK_ENV=${FLASK_ENV:-production}
      - DATABASE_URL=sqlite:////app/instance/app.db
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000/auth/health')"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    networks:
      - mountyhall-network
    # entrypoint: ["tail", "-f", "/dev/null"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: mountyhall-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - mountyhall-network

  sqlite-web:
    image: ghcr.io/coleifer/sqlite-web:latest
    container_name: mountyhall-sqlite-web
    ports:
      - "8080:8080"
    volumes:
      - ./backend/instance:/data
    command: app.db
    restart: unless-stopped
    networks:
      - mountyhall-network

networks:
  mountyhall-network:
    driver: bridge
